services:
  - type: web
    name: sistemafrota
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn sistemafrota.wsgi:application
    envVars:
      - key: DEBUG
        value: 0
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: frota.mov.pro.br localhost 127.0.0.1
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: sistemafrota-db
          property: connectionString
    
databases:
  - name: sistemafrota-db
    databaseName: sistemafrota
    user: sistemafrota_user
    plan: free 