services:
  - type: web
    name: sistemafrota
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    healthCheckTimeout: 100
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sistemafrota-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: sistemafrota.settings
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: "0"
      - key: DATABASE_SSL_MODE
        value: require
      - key: PORT
        value: "10000"

databases:
  - name: sistemafrota-db
    region: oregon
    plan: free
    ipAllowList: []
    postgresMajorVersion: 15
    options:
      maxConnections: 20
      sslMode: require