services:
  - type: web
    name: sistemafrota
    env: docker
    region: oregon
    plan: free
    domains:
      - frota.mov.pro.br
    envVars:
      - key: DEBUG
        value: 1
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: WEB_CONCURRENCY
        value: 4
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: sistemafrota-db
          property: connectionString
      - key: DATABASE_HOST
        fromDatabase:
          name: sistemafrota-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: sistemafrota-db
          property: port
      - key: DJANGO_SETTINGS_MODULE
        value: sistemafrota.settings
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /admin/
    
databases:
  - name: sistemafrota-db
    databaseName: sistemafrota
    user: sistemafrota_user
    plan: free 