services:
  - type: web
    name: sistemafrota
    env: docker
    region: oregon
    plan: free
    domains:
      - frota.mov.pro.br
    envVars:
      - key: DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: frota.mov.pro.br localhost 127.0.0.1 sistemafrota-3.onrender.com
      - key: WEB_CONCURRENCY
        value: 4
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: sistemafrota-db
          property: connectionString
    
databases:
  - name: sistemafrota-db
    databaseName: sistemafrota
    user: sistemafrota_user
    plan: free 