services:
  - type: web
    name: sistemafrota
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sistemafrota.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: frota.mov.pro.br,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: sistemafrota-db
          property: connectionString
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        value: magno.brt8@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
    
databases:
  - name: sistemafrota-db
    databaseName: sistemafrota
    user: sistemafrota_user
    plan: free 