# Generated by Django 5.2.1 on 2025-05-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnh', models.CharField(max_length=20, unique=True, verbose_name='CNH')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('validade_cnh', models.DateField(blank=True, null=True, verbose_name='Validade CNH')),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Peça')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('fornecedor', models.CharField(max_length=200, verbose_name='Fornecedor')),
                ('vale', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Vale')),
                ('data_manutencao', models.DateField(auto_now_add=True, verbose_name='Data da Manutenção')),
                ('orcamento', models.FileField(blank=True, null=True, upload_to='orcamentos/', verbose_name='Orçamento')),
                ('quilometragem', models.IntegerField(verbose_name='Quilometragem')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('tipo_manutencao_1', models.CharField(choices=[('Corretiva', 'Corretiva'), ('Preventiva', 'Preventiva'), ('Personalização', 'Personalização')], max_length=20, verbose_name='Tipo de Manutenção 1')),
                ('tipo_manutencao_2', models.CharField(choices=[('Borracharia', 'Borracharia'), ('Revisão', 'Revisão'), ('Pneus', 'Pneus'), ('Acessórios', 'Acessórios'), ('Manutenção', 'Manutenção'), ('Plotagem', 'Plotagem'), ('Bateria', 'Bateria')], max_length=20, verbose_name='Tipo de Manutenção 2')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.centrodecusto')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='ManutencaoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota.manutencao')),
                ('peca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frota.peca')),
            ],
        ),
        migrations.AddField(
            model_name='manutencao',
            name='pecas',
            field=models.ManyToManyField(through='frota.ManutencaoPeca', to='frota.peca', verbose_name='Peças'),
        ),
        migrations.CreateModel(
            name='ManutencaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota.manutencao')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frota.servico')),
            ],
        ),
        migrations.AddField(
            model_name='manutencao',
            name='servicos',
            field=models.ManyToManyField(through='frota.ManutencaoServico', to='frota.servico', verbose_name='Serviços'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('combustivel', models.CharField(max_length=50, verbose_name='Combustível')),
                ('valor_fipe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor FIPE')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('motivo_inativo', models.CharField(blank=True, choices=[('SEM_OPERACAO', 'Sem Operação'), ('EM_MANUTENCAO', 'Em Manutenção')], max_length=20, null=True, verbose_name='Motivo Inativo')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.motorista', verbose_name='Motorista')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.setor', verbose_name='Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Multa')),
                ('tipo', models.CharField(choices=[('VELOCIDADE', 'Excesso de Velocidade'), ('ESTACIONAMENTO', 'Estacionamento Irregular'), ('SINAL', 'Avançar Sinal'), ('DOCUMENTACAO', 'Documentação Irregular'), ('OUTRAS', 'Outras Infrações')], max_length=20, verbose_name='Tipo da Multa')),
                ('local', models.CharField(max_length=200, verbose_name='Local da Multa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Multa')),
                ('paga', models.BooleanField(default=False, verbose_name='Multa Paga')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.motorista', verbose_name='Motorista Responsável')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='manutencao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota.veiculo', verbose_name='Veículo'),
        ),
    ]
