version: '3.8'

volumes:
  postgres_data:
    external: true
    name: sistemafrota_postgres_data
  static_volume:
    external: true
    name: sistemafrota_static_volume
  media_volume:
    external: true
    name: sistemafrota_media_volume

services:
  web:
    image: magno08/sistemafrota:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - SECRET_KEY=pbkdf2_sha256$600000$dj2Bx7HK9L8Q5M3N$pY6tZ9xK2wR4vF8mE9nJ1hL5sQ7uV3yD
      - ALLOWED_HOSTS=frota.mov.pro.br,localhost,127.0.0.1
      - POSTGRES_DB=sistemafrota
      - POSTGRES_USER=sistemafrota_user
      - POSTGRES_PASSWORD=S3nh4S3gur4!2024
      - DATABASE_URL=postgresql://sistemafrota_user:S3nh4S3gur4!2024@db:5432/sistemafrota
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=magno.brt8@gmail.com
      - EMAIL_HOST_PASSWORD=M@rcela1908
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sistemafrota
      - POSTGRES_USER=sistemafrota_user
      - POSTGRES_PASSWORD=S3nh4S3gur4!2024
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sistemafrota_user -d sistemafrota"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s 